version: '3.8'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "80:80"
    networks:
      - inception
    volumes:
      - ./web:/var/www/html
  wordpress:
    container_name: wp-php
    build: requirements/wordpress/
    networks:
      - inception
    volumes:
      - ./web:/var/www/html
  mariadb: 
    container_name: mariadb
    build: requirements/mariadb/
    networks:
      - inception
networks:
  inception:
    driver: bridge
