version: '3'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "80:80"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
  mariadb: 
    container_name: mariadb
    build: requirements/mariadb/
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/coxer/Documents/Docker/volumes/mariadb_inception
      o: bind
  wordpress:
    driver_opts:
      type: none
      device: /home/coxer/Documents/Docker/volumes/wordpress_inception
      o: bind
